#define CURSOR_num_glyphs 154
#define CURSOR_X_cursor 0
#define CURSOR_arrow 2
#define CURSOR_based_arrow_down 4
#define CURSOR_based_arrow_up 6
#define CURSOR_boat 8
#define CURSOR_bogosity 10
#define CURSOR_bottom_left_corner 12
#define CURSOR_bottom_right_corner 14
#define CURSOR_bottom_side 16
#define CURSOR_bottom_tee 18
#define CURSOR_box_spiral 20
#define CURSOR_center_ptr 22
#define CURSOR_circle 24
#define CURSOR_clock 26
#define CURSOR_coffee_mug 28
#define CURSOR_cross 30
#define CURSOR_cross_reverse 32
#define CURSOR_crosshair 34
#define CURSOR_diamond_cross 36
#define CURSOR_dot 38
#define CURSOR_dotbox 40
#define CURSOR_double_arrow 42
#define CURSOR_draft_large 44
#define CURSOR_draft_small 46
#define CURSOR_draped_box 48
#define CURSOR_exchange 50
#define CURSOR_fleur 52
#define CURSOR_gobbler 54
#define CURSOR_gumby 56
#define CURSOR_hand1 58
#define CURSOR_hand2 60
#define CURSOR_heart 62
#define CURSOR_icon 64
#define CURSOR_iron_cross 66
#define CURSOR_left_ptr 68
#define CURSOR_left_side 70
#define CURSOR_left_tee 72
#define CURSOR_leftbutton 74
#define CURSOR_ll_angle 76
#define CURSOR_lr_angle 78
#define CURSOR_man 80
#define CURSOR_middlebutton 82
#define CURSOR_mouse 84
#define CURSOR_pencil 86
#define CURSOR_pirate 88
#define CURSOR_plus 90
#define CURSOR_question_arrow 92
#define CURSOR_right_ptr 94
#define CURSOR_right_side 96
#define CURSOR_right_tee 98
#define CURSOR_rightbutton 100
#define CURSOR_rtl_logo 102
#define CURSOR_sailboat 104
#define CURSOR_sb_down_arrow 106
#define CURSOR_sb_h_double_arrow 108
#define CURSOR_sb_left_arrow 110
#define CURSOR_sb_right_arrow 112
#define CURSOR_sb_up_arrow 114
#define CURSOR_sb_v_double_arrow 116
#define CURSOR_shuttle 118
#define CURSOR_sizing 120
#define CURSOR_spider 122
#define CURSOR_spraycan 124
#define CURSOR_star 126
#define CURSOR_target 128
#define CURSOR_tcross 130
#define CURSOR_top_left_arrow 132
#define CURSOR_top_left_corner 134
#define CURSOR_top_right_corner 136
#define CURSOR_top_side 138
#define CURSOR_top_tee 140
#define CURSOR_trek 142
#define CURSOR_ul_angle 144
#define CURSOR_umbrella 146
#define CURSOR_ur_angle 148
#define CURSOR_watch 150
#define CURSOR_xterm 152

